name: Hello

on:
  workflow_dispatch:
    inputs:
      Name:
        description: Who to greet
        required: true
        default: 'GitHub Actions'

jobs:
  Hello:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/hello
        with:
          Name: ${{ github.event.inputs.Name }}
